[versions]
springBoot = "2.6.3"
springDM = "1.0.11.RELEASE"
springCloud = "2020.0.4"
graphqlKickstartStarter = "12.0.0"

[libraries]
spring-cloud-depends = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloud" }
spring-boot-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-cloud-stream-kafka = { module = "org.springframework.cloud:spring-cloud-starter-stream-kafka" }
graphql-kickstart-starter = { module = "com.graphql-java-kickstart:graphql-spring-boot-starter", version.ref = "graphqlKickstartStarter" }

jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

[bundles]

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dm = { id = "io.spring.dependency-management", version.ref = "springDM" }