version: '3.9'
name: my-kafka-ui

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8089:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - inner-network
      - outer-network

networks:
  inner-network:
    name: tb-inner-kafka-network
    external: true
  outer-network:
    name: tb-outer-kafka-network
    external: true